import type { ClaudeTriageHints, TriageProfile } from "@/utils/triage-engine";
import type { ProtocolId } from "@/utils/triage-protocols";
import type { PatientProfile, RecommendationResult } from "@/utils/cases";

/**
 * Anthropic-compatible client for the MedNexus AI narrative.
 *
 * Configuration is read at BUNDLE TIME from EXPO_PUBLIC_* environment
 * variables (Expo inlines these when building the JS bundle). No secrets are
 * hardcoded here. Set them in a `.env` / `.env.local` at the project root:
 *
 *   EXPO_PUBLIC_ANTHROPIC_AUTH_TOKEN=<your key>
 *   EXPO_PUBLIC_ANTHROPIC_BASE_URL=https://api.anthropic.com
 *   EXPO_PUBLIC_ANTHROPIC_MODEL=claude-opus-4-8
 *
 * Security note: because the token is baked into the shipped JS bundle, treat
 * it as short-lived and rotate it before/after the hackathon. When no token is
 * configured (or a call fails/times out), the app gracefully falls back to the
 * local deterministic knowledge-network engine — the UI never breaks.
 */

const BASE_URL =
  (process.env.EXPO_PUBLIC_ANTHROPIC_BASE_URL || "https://api.anthropic.com").replace(
    /\/+$/,
    ""
  );
const MODEL =
  process.env.EXPO_PUBLIC_ANTHROPIC_MODEL || "claude-opus-4-8";
const AUTH_TOKEN = process.env.EXPO_PUBLIC_ANTHROPIC_AUTH_TOKEN || "";

const TIMEOUT_MS = 20000;

/** True when a Claude credential is available at build time. */
export function claudeConfigured(): boolean {
  return AUTH_TOKEN.length > 0;
}

/** Human label shown in the UI to indicate the data source. */
export const CLAUDE_LABEL = "Generated by Claude · Anthropic";

export interface ClaudeNarrative {
  summary: string;
  rationale: string[];
  risks: string[];
  flags: string[];
}

const SYMPTOM_CATALOG: Record<string, string> = {
  "chest pain": "cardiac",
  "dyspnea": "respiratory",
  "hypotension": "cardiac",
  tachycardia: "cardiac",
  "kidney injury": "renal",
  hypertension: "cardiovascular",
  confusion: "neurological",
};

function buildSystemPrompt(): string {
  return [
    "You are MedNexus AI, a careful clinical decision-support assistant used inside a hospital operations system.",
    "You receive a de-identified patient profile and a deterministic knowledge-network match (top diagnosis, treatment pathway, recovery/stay estimates, complications).",
    "Your job is to produce a concise, grounded, human-readable clinical narrative in STRICT JSON — no markdown, no fences, no commentary outside the JSON.",
    "You must return exactly this shape:",
    "{\"summary\": string, \"rationale\": [string], \"risks\": [string], \"flags\": [string]}",
    "- summary: 1-2 sentences synthesising the patient picture and the recommended first step.",
    "- rationale: 2-4 bullets explaining the reasoning (why this pathway, what the match suggests).",
    "- risks: 2-3 clinically sensible risks to monitor based on the symptoms.",
    "- flags: 1-3 red-flag cautions (only if genuinely warranted by the profile; otherwise an empty array).",
    "Ground everything in the provided data. Do not invent patient identifiers. Keep clinical language conservative and add patient-safety framing.",
  ].join("\n");
}

/** Extract the first JSON object from a model reply (tolerates code fences). */
function extractJson(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1] : text;
  const start = candidate.search(/\{/);
  if (start === -1) return null;
  try {
    return JSON.parse(candidate.slice(start));
  } catch {
    return null;
  }
}

function normalizeList(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((v): v is string => typeof v === "string").map((s) => s.trim());
}

function parseNarrative(text: string, fallback: RecommendationResult): ClaudeNarrative {
  const data = extractJson(text);
  if (typeof data !== "object" || data === null) {
    return {
      summary: fallback.pathway.label,
      rationale: fallback.pathway.steps.slice(0, 3),
      risks: fallback.complications.slice(0, 3),
      flags: [],
    };
  }
  const obj = data as Record<string, unknown>;
  const rawSummary = typeof obj.summary === "string" ? obj.summary.trim() : "";
  const rationale = normalizeList(obj.rationale);
  const risks = normalizeList(obj.risks);
  const flags = normalizeList(obj.flags);

  return {
    summary: rawSummary || fallback.pathway.label,
    rationale: rationale.length > 0 ? rationale : fallback.pathway.steps.slice(0, 3),
    risks: risks.length > 0 ? risks : fallback.complications.slice(0, 3),
    flags,
  };
}

function flaggedCategories(symptoms: string[]): string[] {
  const seen = new Set<string>();
  for (const s of symptoms) {
    const cat = SYMPTOM_CATALOG[s.toLowerCase()];
    if (cat) seen.add(cat);
  }
  const label: Record<string, string> = {
    cardiac: "Cardiac red-flag pathway",
    respiratory: "Respiratory compromise watch",
    renal: "Renal function monitoring",
    neurological: "Neurological reassessment required",
    cardiovascular: "Blood-pressure escalation watch",
  };
  return [...seen].map((c) => label[c]).filter(Boolean);
}

/**
 * Ask Claude to write the clinical narrative for a patient profile.
 *
 * Returns null (never throws) when no credential is configured or when the
 * request fails/times out — the caller then falls back to the deterministic
 * engine. This keeps the app fully functional offline or without a key.
 */
export async function generateNarrative(
  profile: PatientProfile,
  topMatch: RecommendationResult
): Promise<ClaudeNarrative | null> {
  if (!AUTH_TOKEN) return null;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const res = await fetch(`${BASE_URL}/v1/messages`, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "content-type": "application/json",
        "x-api-key": AUTH_TOKEN,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 800,
        system: buildSystemPrompt(),
        messages: [
          {
            role: "user",
            content: JSON.stringify({
              patient_profile: {
                age: profile.age,
                symptoms: profile.symptoms,
                notes: profile.notes || undefined,
              },
              knowledge_match: {
                diagnosis: topMatch.pathway.label,
                pathway: topMatch.pathway.steps,
                matched_cases: topMatch.matchCount,
                stats: topMatch.stats,
                complications: topMatch.complications,
              },
            }),
          },
        ],
      }),
    });

    if (!res.ok) return null;

    const data = await res.json();
    const text: string | undefined = data?.content?.[0]?.text;
    if (!text) return null;

    const parsed = parseNarrative(text, topMatch);
    if (parsed.flags.length === 0 && flaggedCategories(profile.symptoms).length > 0) {
      parsed.flags = flaggedCategories(profile.symptoms);
    }
    return parsed;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

function buildTriageSystemPrompt(): string {
  return [
    "You are MedNexus AI, a careful patient-facing triage assistant.",
    "You receive a patient's free-text symptom description and their de-identified profile.",
    "Your job is to classify it into ONE of these protocols: 'headache', 'fever', or 'chest_pain'.",
    "If the symptoms clearly suggest emergency-level danger (worst headache of life, chest pain radiating to arm/jaw/back, very high fever with stiff neck or confusion, trouble breathing), set 'urgent' to true.",
    "Respond with STRICT JSON only — no markdown, no fences — shaped exactly like:",
    '{"protocol": "headache" | "fever" | "chest_pain" | null, "urgent": boolean, "reasoning": string}',
    "- protocol: null when the description is not recognisable as any of the three protocols.",
    "- urgent: true only for genuine red-flag patterns that should not be delayed by questions.",
    "- reasoning: one short sentence on why, grounded only in the provided text. Be conservative; never reassure in the reasoning.",
  ].join("\n");
}

function parseTriageHints(text: string): ClaudeTriageHints | null {
  const data = extractJson(text);
  if (typeof data !== "object" || data === null) return null;
  const obj = data as Record<string, unknown>;
  const protocol = ["headache", "fever", "chest_pain"].includes(
    String(obj.protocol || "")
  )
    ? (String(obj.protocol) as ProtocolId)
    : null;
  return {
    protocol,
    urgent: obj.urgent === true,
    reasoning: typeof obj.reasoning === "string" ? obj.reasoning.trim() : "",
  };
}

/**
 * Ask Claude to interpret a patient's free-text symptoms into a triage
 * protocol decision. Returns null (never throws) when no credential is
 * configured or the request fails — the caller must then fall back to the
 * deterministic `routeProtocol`/`isUrgentText` engine in triage-engine.
 */
export async function interpretTriageSymptoms(
  text: string,
  profile: TriageProfile
): Promise<ClaudeTriageHints | null> {
  if (!AUTH_TOKEN) return null;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const res = await fetch(`${BASE_URL}/v1/messages`, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "content-type": "application/json",
        "x-api-key": AUTH_TOKEN,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 400,
        system: buildTriageSystemPrompt(),
        messages: [
          {
            role: "user",
            content: JSON.stringify({
              symptoms_text: text,
              patient_profile: {
                age: profile.age,
                gender: profile.gender || undefined,
                conditions: profile.conditions || [],
                allergies: profile.allergies || [],
                medications: profile.medications || [],
              },
            }),
          },
        ],
      }),
    });

    if (!res.ok) return null;

    const data = await res.json();
    const reply: string | undefined = data?.content?.[0]?.text;
    if (!reply) return null;

    return parseTriageHints(reply);
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}
